#!/usr/bin/env python3
"""Preprocess IBM Synthetic Core Banking data in an AMLSim-style layout.

The pipeline reads the IBM release zip directly, normalizes transactions and
account metadata, creates temporal splits, graph artifacts, prior-only rolling
features, and sanity-check reports under the requested output directory.
"""

from __future__ import annotations

import argparse
import gzip
import json
import zipfile
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import BinaryIO, Iterable

import pandas as pd


EXPECTED_OUTPUTS = [
    "transactions_master.csv.gz",
    "accounts_clean.csv.gz",
    "banks_clean.csv.gz",
    "b2b_clean.csv.gz",
    "node_map.csv.gz",
    "edge_list.csv.gz",
    "account_node_features.csv.gz",
    "model_feature_columns.json",
    "split_label_summary.csv",
    "label_summary.csv",
    "preprocessing_report.json",
]

TXN_RENAME = {
    "Transaction_Number": "txn_id",
    "From_Account": "src_id",
    "To_Account": "dst_id",
    "From_Bank": "src_bank_id",
    "To_Bank": "dst_bank_id",
    "Amount_Paid": "amount",
    "Payment_Currency": "currency",
    "Payment_Format": "payment_format",
    "Transaction_Type": "transaction_type_raw",
    "Is_Laundering": "y",
    "Laundering_Type": "laundering_type",
}

REQUIRED_TXN_COLUMNS = [
    "Transaction_Number",
    "Transaction_Date",
    "Transaction_Time",
    "From_Bank",
    "From_Account",
    "To_Bank",
    "To_Account",
    "Amount_Paid",
    "Payment_Currency",
    "Payment_Format",
    "Transaction_Type",
    "Laundering_Type",
    "Is_Laundering",
]

LEAKAGE_COLUMNS = [
    "transaction_type_raw",
    "laundering_type",
    "y",
    "edge_label",
    "Is_Laundering",
    "Laundering_Type",
    "Transaction_Type",
    "Is_Cheque_Fraud",
    "Is_APP_Fraud",
    "Cheque_Fraudster_ID",
    "APP_Fraudster_ID",
    "APP_Fraud_Sequence_Number",
    # Not generated by this script anymore (see normalize_transaction_chunk); kept forbidden
    # here so this column can never be reclassified as a safe feature if it is reintroduced
    # by a future change or an unexpected upstream/intermediate artifact.
    "transaction_type_model_safe",
]

# Columns that must never appear in the prepared model-facing transaction table at all,
# regardless of LEAKAGE_COLUMNS handling (which only governs the safe-feature manifest).
FORBIDDEN_DERIVED_COLUMNS = {
    "transaction_type_model_safe",
}


@dataclass
class LocatedFiles:
    transactions: str
    companies: str
    people: str
    banks: str
    b2b: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--zip", required=True, type=Path, help="IBM dataset zip file")
    parser.add_argument("--out", required=True, type=Path, help="Output directory")
    parser.add_argument("--chunksize", type=int, default=250_000, help="Transaction rows per chunk")
    parser.add_argument("--sample-rows", type=int, default=None, help="Optional transaction row limit for smoke tests")
    return parser.parse_args()


def valid_member(name: str) -> bool:
    path = Path(name)
    return not name.endswith("/") and "__MACOSX" not in path.parts and not path.name.startswith("._")


def locate_files(zf: zipfile.ZipFile) -> LocatedFiles:
    members = [n for n in zf.namelist() if valid_member(n)]
    lower = {n: n.lower() for n in members}

    def one(predicate, label: str) -> str:
        matches = [n for n, low in lower.items() if predicate(low)]
        if not matches:
            raise FileNotFoundError(f"Could not locate {label} in {zf.filename}")
        matches.sort(key=lambda n: (len(n), n))
        return matches[0]

    return LocatedFiles(
        transactions=one(lambda s: "bank_xfers" in s and s.endswith((".csv.gz", ".csv")), "main transaction file"),
        companies=one(lambda s: "liquid_accts_companies" in s and s.endswith(".csv"), "company account file"),
        people=one(lambda s: "liquid_accts_people" in s and s.endswith(".csv"), "people account file"),
        banks=one(lambda s: "banks" in s and s.endswith(".csv"), "bank file"),
        b2b=one(lambda s: "b2b" in s and s.endswith(".csv"), "B2B file"),
    )


def open_member_binary(zf: zipfile.ZipFile, member: str) -> BinaryIO:
    raw = zf.open(member)
    if member.lower().endswith(".gz"):
        return gzip.GzipFile(fileobj=raw)
    return raw


def read_csv_member(zf: zipfile.ZipFile, member: str, **kwargs) -> pd.DataFrame:
    kwargs.setdefault("encoding", "utf-8")
    kwargs.setdefault("encoding_errors", "replace")
    with open_member_binary(zf, member) as fh:
        return pd.read_csv(fh, **kwargs)


def clean_account_frame(df: pd.DataFrame, account_kind: str) -> pd.DataFrame:
    df = df.copy()
    df.columns = [c.strip() for c in df.columns]
    df["account_kind"] = account_kind
    df["Account_ID"] = df["Account_ID"].astype("string")
    return df.drop_duplicates(subset=["Account_ID"], keep="first")


def assign_split(ts: pd.Series) -> pd.Series:
    month = ts.dt.to_period("M").astype("string")
    split = pd.Series("unused", index=ts.index, dtype="string")
    split[month.isin(["2025-06", "2025-07"])] = "train"
    split[month == "2025-08"] = "val"
    split[month == "2025-09"] = "test"
    return split


def add_prior_features(
    df: pd.DataFrame,
    count_state: dict[str, int],
    amount_state: dict[str, float],
    id_col: str,
    amount_col: str,
    prefix: str,
) -> None:
    ids = df[id_col].astype("string")
    amounts = pd.to_numeric(df[amount_col], errors="coerce").fillna(0.0)

    prior_counts = ids.map(count_state).fillna(0).astype("int64")
    prior_sums = ids.map(amount_state).fillna(0.0).astype("float64")
    within_counts = ids.groupby(ids, sort=False).cumcount().astype("int64")
    within_sums = amounts.groupby(ids, sort=False).cumsum() - amounts

    prev_counts = prior_counts + within_counts
    prev_sums = prior_sums + within_sums
    df[f"{prefix}_prev_txn_count"] = prev_counts
    df[f"{prefix}_prev_amount_sum"] = prev_sums
    df[f"{prefix}_prev_amount_mean"] = (prev_sums / prev_counts.replace(0, pd.NA)).fillna(0.0)

    grouped = pd.DataFrame({"id": ids, "amount": amounts}).groupby("id", sort=False)["amount"].agg(["count", "sum"])
    for account_id, row in grouped.iterrows():
        count_state[str(account_id)] += int(row["count"])
        amount_state[str(account_id)] += float(row["sum"])


def transaction_chunks(zf: zipfile.ZipFile, member: str, chunksize: int) -> Iterable[pd.DataFrame]:
    with open_member_binary(zf, member) as fh:
        yield from pd.read_csv(fh, chunksize=chunksize, encoding="utf-8", encoding_errors="replace")


def normalize_transaction_chunk(df: pd.DataFrame) -> pd.DataFrame:
    missing = sorted(set(REQUIRED_TXN_COLUMNS) - set(df.columns))
    if missing:
        raise ValueError(f"Transaction file is missing required columns: {missing}")

    df = df.copy()
    df["timestamp"] = pd.to_datetime(
        df["Transaction_Date"].astype(str) + " " + df["Transaction_Time"].astype(str),
        errors="coerce",
    )
    df = df.rename(columns=TXN_RENAME)
    df["txn_id"] = df["txn_id"].astype("string")
    df["src_id"] = df["src_id"].astype("string")
    df["dst_id"] = df["dst_id"].astype("string")
    df["amount"] = pd.to_numeric(df["amount"], errors="coerce")
    df["y"] = pd.to_numeric(df["y"], errors="coerce").fillna(0).astype("int8")
    df["edge_label"] = df["y"]
    df["split"] = assign_split(df["timestamp"])
    return df


def assert_no_forbidden_columns(df: pd.DataFrame, context: str) -> None:
    present = FORBIDDEN_DERIVED_COLUMNS & set(df.columns)
    if present:
        raise SystemExit(
            f"ERROR: forbidden leakage column(s) {sorted(present)} present in {context}; "
            "these must never be written to prepared model-facing output"
        )


def update_summary(summary: dict, df: pd.DataFrame) -> None:
    summary["total_transaction_rows"] += int(len(df))
    summary["laundering_positive_rows"] += int(df["y"].sum())
    summary["unique_source_accounts"].update(df["src_id"].dropna().astype(str))
    summary["unique_destination_accounts"].update(df["dst_id"].dropna().astype(str))
    summary["all_transaction_accounts"].update(df["src_id"].dropna().astype(str))
    summary["all_transaction_accounts"].update(df["dst_id"].dropna().astype(str))
    summary["split_counts"].update(df["split"].astype(str))
    summary["label_counts"].update(df["y"].astype(int).astype(str))
    for split, part in df.groupby("split", dropna=False):
        for label, count in part["y"].value_counts(dropna=False).items():
            summary["split_label_counts"][(str(split), int(label))] += int(count)
    for col, count in df.isna().sum().items():
        summary["missing_value_counts"][col] += int(count)
    min_ts = df["timestamp"].min()
    max_ts = df["timestamp"].max()
    if pd.notna(min_ts):
        summary["min_timestamp"] = min(summary["min_timestamp"], min_ts) if summary["min_timestamp"] is not None else min_ts
    if pd.notna(max_ts):
        summary["max_timestamp"] = max(summary["max_timestamp"], max_ts) if summary["max_timestamp"] is not None else max_ts


def write_transactions_master(
    zf: zipfile.ZipFile,
    member: str,
    out_path: Path,
    chunksize: int,
    sample_rows: int | None,
) -> dict:
    src_counts: dict[str, int] = defaultdict(int)
    src_sums: dict[str, float] = defaultdict(float)
    dst_counts: dict[str, int] = defaultdict(int)
    dst_sums: dict[str, float] = defaultdict(float)
    summary = {
        "total_transaction_rows": 0,
        "laundering_positive_rows": 0,
        "unique_source_accounts": set(),
        "unique_destination_accounts": set(),
        "all_transaction_accounts": set(),
        "split_counts": Counter(),
        "label_counts": Counter(),
        "split_label_counts": Counter(),
        "missing_value_counts": Counter(),
        "min_timestamp": None,
        "max_timestamp": None,
    }

    wrote_header = False
    remaining = sample_rows
    with gzip.open(out_path, "wt", newline="") as out_fh:
        for chunk in transaction_chunks(zf, member, chunksize):
            if remaining is not None:
                if remaining <= 0:
                    break
                chunk = chunk.head(remaining)
                remaining -= len(chunk)
            if chunk.empty:
                continue

            tx = normalize_transaction_chunk(chunk)
            tx = tx.sort_values(["timestamp", "txn_id"], kind="mergesort").reset_index(drop=True)
            add_prior_features(tx, src_counts, src_sums, "src_id", "amount", "src")
            add_prior_features(tx, dst_counts, dst_sums, "dst_id", "amount", "dst")
            assert_no_forbidden_columns(tx, "prepared transactions_master.csv.gz chunk")
            update_summary(summary, tx)
            tx.to_csv(out_fh, index=False, header=not wrote_header)
            wrote_header = True

    return summary


def build_node_map(accounts: pd.DataFrame, transaction_accounts: set[str]) -> pd.DataFrame:
    account_ids = set(accounts["Account_ID"].dropna().astype(str))
    account_ids.update(transaction_accounts)
    return pd.DataFrame({"account_id": sorted(account_ids)}).assign(node_id=lambda d: range(len(d)))


def build_account_features(master_path: Path, accounts: pd.DataFrame, node_map: pd.DataFrame) -> pd.DataFrame:
    usecols = ["src_id", "dst_id", "amount"]
    sent_parts = []
    recv_parts = []
    for chunk in pd.read_csv(master_path, usecols=usecols, chunksize=500_000):
        chunk["amount"] = pd.to_numeric(chunk["amount"], errors="coerce").fillna(0.0)
        sent_parts.append(chunk.groupby(chunk["src_id"].astype("string"))["amount"].agg(sent_count="count", sent_amount_sum="sum"))
        recv_parts.append(chunk.groupby(chunk["dst_id"].astype("string"))["amount"].agg(recv_count="count", recv_amount_sum="sum"))

    sent = pd.concat(sent_parts).groupby(level=0).sum() if sent_parts else pd.DataFrame()
    recv = pd.concat(recv_parts).groupby(level=0).sum() if recv_parts else pd.DataFrame()
    features = node_map.copy()
    features["account_id"] = features["account_id"].astype("string")
    features = features.merge(accounts, left_on="account_id", right_on="Account_ID", how="left")
    features = features.merge(sent, left_on="account_id", right_index=True, how="left")
    features = features.merge(recv, left_on="account_id", right_index=True, how="left")
    for col in ["sent_count", "recv_count", "sent_amount_sum", "recv_amount_sum"]:
        features[col] = features[col].fillna(0)
    features["out_degree"] = features["sent_count"].astype("int64")
    features["in_degree"] = features["recv_count"].astype("int64")
    return features


def build_edge_list(master_path: Path, node_map: pd.DataFrame, out_path: Path) -> None:
    mapper = dict(zip(node_map["account_id"].astype(str), node_map["node_id"].astype("int64")))
    columns = ["txn_id", "src_id", "dst_id", "timestamp", "amount", "edge_label", "laundering_type", "split"]
    wrote_header = False
    with gzip.open(out_path, "wt", newline="") as out_fh:
        for chunk in pd.read_csv(master_path, usecols=columns, chunksize=500_000):
            chunk["src_node"] = chunk["src_id"].astype(str).map(mapper)
            chunk["dst_node"] = chunk["dst_id"].astype(str).map(mapper)
            edge = chunk[["txn_id", "src_node", "dst_node", "timestamp", "amount", "edge_label", "laundering_type", "split"]]
            edge.to_csv(out_fh, index=False, header=not wrote_header)
            wrote_header = True


def write_feature_manifest(out_dir: Path, master_columns: list[str]) -> None:
    id_columns = ["txn_id", "src_id", "dst_id", "src_bank_id", "dst_bank_id"]
    graph_columns = ["src_node", "dst_node", "edge_label"]
    label_columns = ["y", "laundering_type"]
    safe_feature_columns = [
        c
        for c in master_columns
        if c
        not in set(LEAKAGE_COLUMNS)
        | set(id_columns)
        | set(label_columns)
        | set(graph_columns)
        | {"timestamp", "Transaction_Date", "Transaction_Time"}
    ]
    manifest = {
        "safe_feature_columns": safe_feature_columns,
        "label_columns": label_columns,
        "leakage_columns": sorted(set(LEAKAGE_COLUMNS)),
        "id_columns": id_columns,
        "graph_columns": graph_columns,
    }
    (out_dir / "model_feature_columns.json").write_text(json.dumps(manifest, indent=2) + "\n")


def write_summaries(out_dir: Path, summary: dict, accounts: pd.DataFrame, located: LocatedFiles) -> None:
    split_rows = [
        {"split": split, "y": label, "rows": count}
        for (split, label), count in sorted(summary["split_label_counts"].items())
    ]
    pd.DataFrame(split_rows).to_csv(out_dir / "split_label_summary.csv", index=False)
    pd.DataFrame(
        [{"y": int(label), "rows": int(count)} for label, count in sorted(summary["label_counts"].items())]
    ).to_csv(out_dir / "label_summary.csv", index=False)

    report = {
        "input_files": located.__dict__,
        "total_transaction_rows": summary["total_transaction_rows"],
        "date_range": {
            "min": summary["min_timestamp"].isoformat() if summary["min_timestamp"] is not None else None,
            "max": summary["max_timestamp"].isoformat() if summary["max_timestamp"] is not None else None,
        },
        "unique_source_accounts": len(summary["unique_source_accounts"]),
        "unique_destination_accounts": len(summary["unique_destination_accounts"]),
        "total_unique_accounts": int(accounts["Account_ID"].nunique()),
        "total_unique_accounts_in_transactions": len(summary["all_transaction_accounts"]),
        "laundering_positive_rows": summary["laundering_positive_rows"],
        "split_counts": dict(summary["split_counts"]),
        "label_distribution_by_split": [
            {"split": split, "y": label, "rows": count}
            for (split, label), count in sorted(summary["split_label_counts"].items())
        ],
        "missing_value_counts": dict(summary["missing_value_counts"]),
        "output_files": EXPECTED_OUTPUTS,
    }
    (out_dir / "preprocessing_report.json").write_text(json.dumps(report, indent=2) + "\n")


def main() -> None:
    args = parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(args.zip) as zf:
        located = locate_files(zf)

        people = clean_account_frame(read_csv_member(zf, located.people), "person")
        companies = clean_account_frame(read_csv_member(zf, located.companies), "company")
        accounts = pd.concat([people, companies], ignore_index=True).drop_duplicates(subset=["Account_ID"], keep="first")
        banks = read_csv_member(zf, located.banks)
        b2b = read_csv_member(zf, located.b2b)

        accounts.to_csv(args.out / "accounts_clean.csv.gz", index=False, compression="gzip")
        banks.to_csv(args.out / "banks_clean.csv.gz", index=False, compression="gzip")
        b2b.to_csv(args.out / "b2b_clean.csv.gz", index=False, compression="gzip")

        master_path = args.out / "transactions_master.csv.gz"
        summary = write_transactions_master(
            zf,
            located.transactions,
            master_path,
            chunksize=args.chunksize,
            sample_rows=args.sample_rows,
        )

    node_map = build_node_map(accounts, summary["all_transaction_accounts"])
    node_map.to_csv(args.out / "node_map.csv.gz", index=False, compression="gzip")

    build_edge_list(master_path, node_map, args.out / "edge_list.csv.gz")
    account_features = build_account_features(master_path, accounts, node_map)
    account_features.to_csv(args.out / "account_node_features.csv.gz", index=False, compression="gzip")

    master_columns = pd.read_csv(master_path, nrows=0).columns.tolist()
    write_feature_manifest(args.out, master_columns)
    write_summaries(args.out, summary, accounts, located)

    print(f"Wrote {len(EXPECTED_OUTPUTS)} preprocessing outputs to {args.out}")


if __name__ == "__main__":
    main()
